### PR TITLE
Switch light and dark mode

### LINKED ISSUE #26: Support to switch between light and dark mode
We use this very helpful tool for screenshot automation. As we want to take screenshots in both dark and light modes we need to change the device appearence.

We tried to achieve this using the following code snippet which does not work because `AndroidDevice` and `IosDevice` are not exported members of the package and can not be accessed.

```
  final configs = [
      {'locale': 'de', 'skin': 'dark'},
      {'locale': 'de', 'skin': 'light'},
  ];

  final emu = await Emulators.build();

  await emu.forEach([
    'pixel9_screenshot',
    // 'iPhone 16 Pro',
  ])((device) async {
    for (final c in configs) {
      if(c['appearance'] == 'dark') {
        if (device.platform is AndroidDevice) { // ⚠️ does not compile as AndroidDevice can not be imported
          await emu.toolchain.adb(["shell", "cmd uimode night yes"]).string();
        } else if (device.platform is IosDevice) { // // ⚠️ does not compile as IosDevice can not be imported
          await emu.toolchain.simctl(['ui', device.state.id, 'appearance', 'dark']).string();
        } else {
          throw Exception('Unsupported platform for dark mode');
        }
      } else {
        if (device.platform is AndroidDevice) {
          await emu.toolchain.adb(["shell", "cmd uimode night no"]).string();
        } else if (device.platform is IosDevice) {
          await emu.toolchain.simctl(['ui', device.state.id, 'appearance', 'light']).string();
        } else {
          throw Exception('Unsupported platform for dark mode');
        }
      }
```

For us it would be very convenient if the `DevicePlatform` could implement a method to change the appearance. Then `AndroidDevice` and `IosDevice` could both implement this method using either `adb` or `simctl` commands.

If this sounds ok to you I can try to implement a PR for this. What do you think?

### PR DESCRIPTION
**Pull request by timaebi**
This MR:
- adds feature to switch between dark and light mode
- makes the status bar more clean
- upgrades dependencies

fixes #26

### CODE REVIEW

File: lib/src/device/platforms/android_device.dart [hunk 1]
```diff
@@ -157,6 +158,22 @@ class AndroidDevice implements PlatformDevice {
...
+  @override
+  DeviceIO<Unit> setAppearance(Appearance appearance) {
+    final yesOrNo = switch (appearance) {
+      Appearance.dark => "yes",
+      Appearance.light => "no",
+    };
+    return DeviceIO.tryCatch(
+      () => toolchain.adb(["shell", "cmd uimode night $yesOrNo"]).string(),
+      (err, stackTrace) => DeviceError.toolchainFailure(
+        op: 'screenshot',
```
Comment (tim-smart) [inline lib/src/device/platforms/android_device.dart:171]:
```suggestion
        op: 'setAppearance',
```

File: lib/src/device/platforms/ios_device.dart [hunk 2]
```diff
@@ -102,6 +102,22 @@ class IosDevice implements PlatformDevice {
...
+  @override
+  DeviceIO<Unit> setAppearance(Appearance appearance) {
+    final darkOrLight = switch (appearance) {
+      Appearance.dark => "dark",
+      Appearance.light => "light",
+    };
+    return DeviceIO.tryCatch(
+          () => toolchain.simctl(['ui', state.id, 'appearance', darkOrLight]).string(),
+          (err, stackTrace) => DeviceError.toolchainFailure(
+        op: 'screenshot',
```
Comment (tim-smart) [inline lib/src/device/platforms/ios_device.dart:115]:
```suggestion
        op: 'setAppearance',
```

**Review by tim-smart — CHANGES_REQUESTED** [review]

**Review by tim-smart — APPROVED** [review]
